<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="gallery">
	<div class="btn-group">
		<?php if(isset($back)) { ?>
	   <a class="btn" title="<?php _e('Back'); ?>" href="<?php echo $this->url('', array('action' => 'index')); ?>"><i class="icon-arrow-left"></i> <?php _e('Back'); ?></a>
	   <?php } ?>
		<a class="btn" title="<?php _e('Add Category'); ?>" href="<?php echo $this->url('', array('controller' => 'category', 'action' => 'update')); ?>"><i class="icon-list-alt"></i> <?php _e('Add Category'); ?></a>
		<a class="btn" title="<?php _e('Add Album'); ?>" href="<?php echo $this->url('', array('controller' => 'album', 'action' => 'update')); ?>"><i class="icon-folder-open"></i> <?php _e('Add Album'); ?></a>
	   <a class="btn" title="<?php _e('Add Photo'); ?>" href="<?php echo $this->url('', array('controller' => 'photo', 'action' => 'update')); ?>"><i class="icon-picture"></i> <?php _e('Add Photo'); ?></a>
	</div>
	<h3><?php _e('List of albums'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Title'); ?></th>
			<th><?php _e('Category'); ?></th>
			<th><?php _e('Author'); ?></th>
			<th><?php _e('Create'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($albums as $album) { ?>
		<tr>
			<td><?php echo $this->escape($album['id']); ?></td>
			<td><?php echo $this->escape($album['title']); ?></td>
			<td><a title="<?php echo $this->escape($album['categorytitle']); ?>" href="<?php echo $this->url('', array('controller' => 'album', 'action' => 'index', 'category' => $album['categoryid'])); ?>"><?php echo $this->escape($album['categorytitle']); ?></a></td>
			<td><a title="<?php echo $this->escape($album['identity']); ?>" href="<?php echo $this->url('', array('controller' => 'album', 'action' => 'index', 'author' => $album['author'])); ?>"><?php echo $this->escape($album['identity']); ?></a></td>
			<td><?php echo $this->escape($album['create']); ?></td>
			<td>
				<div class="btn-group">
					<a class="btn" title="<?php _e('Add photo'); ?>" href="<?php echo $this->url('', array('controller' => 'photo', 'action' => 'updates', 'album' => $album['id'])); ?>"><i class="icon-edit"></i> <?php _e('Add photo'); ?></a>
					<a class="btn" title="<?php _e('Photos'); ?>" href="<?php echo $this->url('', array('controller' => 'photo', 'action' => 'index', 'album' => $album['id'])); ?>"><i class="icon-edit"></i> <?php _e('Photos'); ?></a>
					<a class="btn" title="<?php _e('View'); ?>" href="<?php echo $this->url('.gallery', array('module' => $module, 'controller' => 'album', 'alias' => $this->escape($album['alias']))); ?>"><i class="icon-eye-open"></i> <?php _e('View'); ?></a>
					<a class="btn" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('controller' => 'album', 'action' => 'update', 'id' => $album['id'])); ?>"><i class="icon-edit"></i> <?php _e('Edit'); ?></a>
					<a class="btn" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('controller' => 'album', 'action' => 'delete', 'id' => $album['id'])); ?>"><i class="icon-trash"></i> <?php _e('Delete'); ?></a>
				</div>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
</div>