<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="gallery">
	<div class="galleryWriter">
		<table class="table table-striped table-bordered table-condensed">
			<thead>
				<th><?php _e('List of Photographers'); ?></th>
			</thead>
			<tbody>
				<?php foreach($photographers as $photographer) { ?>
				<tr>
					<td class="top"><a title="<?php echo $photographer['identity']; ?>" href="<?php echo $this->url('.gallery',  array('module' => $module, 'controller' => 'photographer','action' => 'profile', 'alias' => $this->escape($photographer['identity']))); ?>"><?php echo $this->escape($photographer['identity']); ?></a></td>
					<td class="top"><?php echo $this->escape($photographer['count']); ?></td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
	<div class="paginator"></div>
</div>