<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="gallery"> 
	<div class="photos">
	    <h4><?php _e('List of Photos'); ?></h4>
       <ul class="thumbnails">
		 <?php foreach($photos as $photo) { ?>
			 <li class="<?php echo $config['album_columns']; ?>">
				 <a class="thumbnail" title="<?php echo $this->escape($photo['title']); ?>" href="<?php echo $photo['url']; ?>" >
					 <img src="<?php echo $photo['thumburl']; ?>" alt="<?php echo $this->escape($photo['title']); ?>">
				 </a>
				 <?php if($config['album_title']) { ?><h5><?php echo $this->escape($photo['title']); ?></h5><?php } ?>
			 </li>
	    <?php } ?>
       </ul>
	</div>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
	<?php include $this->template('front/photo'); ?>
</div>